<?php
/**
 * OptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\Checkout
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * klarna-checkout
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20200626163101
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Klarna\Checkout;

/**
 * OptionsTest Class Doc Comment
 *
 * @category    Class
 * @description Options
 * @package     Klarna\Checkout
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Options"
     */
    public function testOptions()
    {
    }

    /**
     * Test attribute "acquiring_channel"
     */
    public function testPropertyAcquiringChannel()
    {
    }

    /**
     * Test attribute "allow_separate_shipping_address"
     */
    public function testPropertyAllowSeparateShippingAddress()
    {
    }

    /**
     * Test attribute "color_button"
     */
    public function testPropertyColorButton()
    {
    }

    /**
     * Test attribute "color_button_text"
     */
    public function testPropertyColorButtonText()
    {
    }

    /**
     * Test attribute "color_checkbox"
     */
    public function testPropertyColorCheckbox()
    {
    }

    /**
     * Test attribute "color_checkbox_checkmark"
     */
    public function testPropertyColorCheckboxCheckmark()
    {
    }

    /**
     * Test attribute "color_header"
     */
    public function testPropertyColorHeader()
    {
    }

    /**
     * Test attribute "color_link"
     */
    public function testPropertyColorLink()
    {
    }

    /**
     * Test attribute "date_of_birth_mandatory"
     */
    public function testPropertyDateOfBirthMandatory()
    {
    }

    /**
     * Test attribute "shipping_details"
     */
    public function testPropertyShippingDetails()
    {
    }

    /**
     * Test attribute "title_mandatory"
     */
    public function testPropertyTitleMandatory()
    {
    }

    /**
     * Test attribute "additional_checkbox"
     */
    public function testPropertyAdditionalCheckbox()
    {
    }

    /**
     * Test attribute "national_identification_number_mandatory"
     */
    public function testPropertyNationalIdentificationNumberMandatory()
    {
    }

    /**
     * Test attribute "additional_merchant_terms"
     */
    public function testPropertyAdditionalMerchantTerms()
    {
    }

    /**
     * Test attribute "phone_mandatory"
     */
    public function testPropertyPhoneMandatory()
    {
    }

    /**
     * Test attribute "radius_border"
     */
    public function testPropertyRadiusBorder()
    {
    }

    /**
     * Test attribute "allowed_customer_types"
     */
    public function testPropertyAllowedCustomerTypes()
    {
    }

    /**
     * Test attribute "show_subtotal_detail"
     */
    public function testPropertyShowSubtotalDetail()
    {
    }

    /**
     * Test attribute "additional_checkboxes"
     */
    public function testPropertyAdditionalCheckboxes()
    {
    }

    /**
     * Test attribute "require_validate_callback_success"
     */
    public function testPropertyRequireValidateCallbackSuccess()
    {
    }

    /**
     * Test attribute "vat_removed"
     */
    public function testPropertyVatRemoved()
    {
    }

    /**
     * Test attribute "verify_national_identification_number"
     */
    public function testPropertyVerifyNationalIdentificationNumber()
    {
    }

    /**
     * Test attribute "show_vat_registration_number_field"
     */
    public function testPropertyShowVatRegistrationNumberField()
    {
    }
}
