<?php
/**
 * OrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\Checkout
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * klarna-checkout
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20200626163101
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Klarna\Checkout;

/**
 * OrderTest Class Doc Comment
 *
 * @category    Class
 * @description Order
 * @package     Klarna\Checkout
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Order"
     */
    public function testOrder()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "purchase_country"
     */
    public function testPropertyPurchaseCountry()
    {
    }

    /**
     * Test attribute "purchase_currency"
     */
    public function testPropertyPurchaseCurrency()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "shipping_address"
     */
    public function testPropertyShippingAddress()
    {
    }

    /**
     * Test attribute "order_amount"
     */
    public function testPropertyOrderAmount()
    {
    }

    /**
     * Test attribute "order_tax_amount"
     */
    public function testPropertyOrderTaxAmount()
    {
    }

    /**
     * Test attribute "order_lines"
     */
    public function testPropertyOrderLines()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "merchant_urls"
     */
    public function testPropertyMerchantUrls()
    {
    }

    /**
     * Test attribute "html_snippet"
     */
    public function testPropertyHtmlSnippet()
    {
    }

    /**
     * Test attribute "merchant_reference1"
     */
    public function testPropertyMerchantReference1()
    {
    }

    /**
     * Test attribute "merchant_reference2"
     */
    public function testPropertyMerchantReference2()
    {
    }

    /**
     * Test attribute "started_at"
     */
    public function testPropertyStartedAt()
    {
    }

    /**
     * Test attribute "completed_at"
     */
    public function testPropertyCompletedAt()
    {
    }

    /**
     * Test attribute "last_modified_at"
     */
    public function testPropertyLastModifiedAt()
    {
    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {
    }

    /**
     * Test attribute "attachment"
     */
    public function testPropertyAttachment()
    {
    }

    /**
     * Test attribute "external_payment_methods"
     */
    public function testPropertyExternalPaymentMethods()
    {
    }

    /**
     * Test attribute "external_checkouts"
     */
    public function testPropertyExternalCheckouts()
    {
    }

    /**
     * Test attribute "shipping_countries"
     */
    public function testPropertyShippingCountries()
    {
    }

    /**
     * Test attribute "shipping_options"
     */
    public function testPropertyShippingOptions()
    {
    }

    /**
     * Test attribute "merchant_data"
     */
    public function testPropertyMerchantData()
    {
    }

    /**
     * Test attribute "gui"
     */
    public function testPropertyGui()
    {
    }

    /**
     * Test attribute "merchant_requested"
     */
    public function testPropertyMerchantRequested()
    {
    }

    /**
     * Test attribute "selected_shipping_option"
     */
    public function testPropertySelectedShippingOption()
    {
    }

    /**
     * Test attribute "recurring"
     */
    public function testPropertyRecurring()
    {
    }

    /**
     * Test attribute "recurring_token"
     */
    public function testPropertyRecurringToken()
    {
    }

    /**
     * Test attribute "recurring_description"
     */
    public function testPropertyRecurringDescription()
    {
    }

    /**
     * Test attribute "billing_countries"
     */
    public function testPropertyBillingCountries()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }
}
