<?php
/**
 * RecurringOrderRequestV1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\Checkout
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * klarna-checkout
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20200626163101
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Klarna\Checkout;

/**
 * RecurringOrderRequestV1Test Class Doc Comment
 *
 * @category    Class
 * @description RecurringOrderRequestV1
 * @package     Klarna\Checkout
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RecurringOrderRequestV1Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RecurringOrderRequestV1"
     */
    public function testRecurringOrderRequestV1()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "cart"
     */
    public function testPropertyCart()
    {
    }

    /**
     * Test attribute "merchant"
     */
    public function testPropertyMerchant()
    {
    }

    /**
     * Test attribute "merchant_reference"
     */
    public function testPropertyMerchantReference()
    {
    }

    /**
     * Test attribute "purchase_country"
     */
    public function testPropertyPurchaseCountry()
    {
    }

    /**
     * Test attribute "purchase_currency"
     */
    public function testPropertyPurchaseCurrency()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "shipping_address"
     */
    public function testPropertyShippingAddress()
    {
    }
}
